name: Build Muufin (Android)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  android:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Grant Gradle wrapper permission
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug

      - name: Upload Debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: muufin-android-debug-apk
          path: app/build/outputs/apk/debug/*.apk

      # ----------------------------
      # Not available yet.
      # ----------------------------
#      - name: Decode keystore (release)
#        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
#        run: |
#          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > ${{ github.workspace }}/keystore.jks
#
#      - name: Build Release APK
#        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
#        env:
#          ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/keystore.jks
#          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
#          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
#          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
#        run: ./gradlew :app:assembleRelease
#
#      - name: Upload Release APK artifact
#        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
#        uses: actions/upload-artifact@v4
#        with:
#          name: muufin-android-release-apk
#          path: app/build/outputs/apk/release/*.apk
